[valex]
user = {{VALEX_USER}}
group = {{VALEX_USERGROUP}}

listen = {{VALEX_FPM_SOCKET_PATH}}
listen.owner = {{VALEX_FPM_SOCKET_OWNER}}
listen.group = {{VALEX_FPM_SOCKET_GROUP}}
listen.mode = 0660

pm = dynamic
pm.max_children = 50
pm.start_servers = 2
pm.max_spare_servers = 4
pm.min_spare_servers = 1
pm.max_requests = 500
pm.process_idle_timeout = 10s
